# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build TypeScript code
RUN npm run build

# Set environment variables
ENV NODE_ENV=production

# Command to run the server
CMD ["node", "build/index.js"]
